[package]
name = 'swap'
version = '1.0.3'
license = "Apache-2.0"
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
swap = "0xf63d44bb4564c8ccd96916b2800b4fab2917d61f79faa6bfd9d14c2c19d4bf2f"

#[dependencies.lp]
#local = "./lp"
#
#[dependencies.init]
#local = "./init"
